sudo: required
dist: trusty
language: elixir
elixir:
  - "1.4.5"
otp_release:
  - "19.3"

env:
 global:
   - MIX_ENV=test

script:
  - "MIX_ENV=test mix do deps.get, test && mix compile && mix coveralls.travis"
